### PR TITLE
Fix broken EventDateSort causing blank or missing events on calendar

### PR DESCRIPTION
**Pull request by Starholme**
Hi,
I believe I've found and solved the cause of some issues. On the City of Prince Albert website we are using this event module, and it stopped displaying events on a month. There didn't seem to be any rhyme or reason to which months did or did not work.
I came across #48 when looking for solutions, and decided to dig into the code myself. The only way I was able to reproduce the issue was by copying my production event data into my development environment and patch up the module/user id's.

Line 350 in EventController.vb was throwing an exception: Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results

The cast from a boolean to a integer on line 666 could only return 0 or -1, never +1. I suspect it almost never causes problems because events don't change start dates very often(So they are sorted already when they come from the db), and any sort with very few items will use an insertion sort, which doesn't really care. Only when there is enough that it hits something like quicksort/heap/etc, AND items are out of order, does it explode.

I suspect but cannot prove that this is the cause of #48, #46, #39, #19.

Could also be related to #47.

Really, anytime that 'some' events were missing or 'all' events were missing in a bug report, this could be the cause. It's very data dependent.

If you would like a copy of my data to test/verify with, please contact me at rdelainey@citypa.com and I'll take the time to anonymize it.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/DNNCommunity/DNN.Events/pull/49%23issuecomment-299284914%22%2C%20%22https%3A//github.com/DNNCommunity/DNN.Events/pull/49%23issuecomment-299392037%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/DNNCommunity/DNN.Events/pull/49%23issuecomment-299284914%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40EPTamminga%20Do%20you%20need%20anything%20else%20from%20me%20to%20get%20this%20pull%20request%20moving%3F%20I%27m%20pretty%20new%20to%20the%20open%20source%20world.%22%2C%20%22created_at%22%3A%20%222017-05-04T19%3A26%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/1916332%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Starholme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40Starholme%20%3A%20no%2C%20no%20need.%20Thank%20you%20for%20your%20work.%5Cr%5CnI%20just%20need%20to%20allocate%20some%20time%20myself%20to%20verify%20and%20create%20a%20new%20release%20by%20going%20over%20a%20number%20of%20issues%20and%20evaluate%20them.%20In%20the%20mean%20time%2C%20you%20are%20perfectly%20safe%20by%20having%20your%20own%20modified%20version%20and%20switch%20over%20to%20a%20new%20release%20once%20it%20comes%20around.%22%2C%20%22created_at%22%3A%20%222017-05-05T06%3A24%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/5859855%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/EPTamminga%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/DNNCommunity/DNN.Events/pull/49#issuecomment-299284914'>General Comment</a></b>
- <a href='https://github.com/Starholme'></a> @EPTamminga Do you need anything else from me to get this pull request moving? I'm pretty new to the open source world.
- <a href='https://github.com/EPTamminga'></a> @Starholme : no, no need. Thank you for your work.
I just need to allocate some time myself to verify and create a new release by going over a number of issues and evaluate them. In the mean time, you are perfectly safe by having your own modified version and switch over to a new release once it comes around.

<a href='https://www.codereviewhub.com/DNNCommunity/DNN.Events/pull/49?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/DNNCommunity/DNN.Events/pull/49?approve=1'></a>&nbsp;<a href='https://github.com/DNNCommunity/DNN.Events/pull/49'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by EPTamminga** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/DNNCommunity/DNN.Events/pull/49'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Starholme** [comment]
@EPTamminga Do you need anything else from me to get this pull request moving? I'm pretty new to the open source world.

**Comment by EPTamminga** [comment]
@Starholme : no, no need. Thank you for your work.
I just need to allocate some time myself to verify and create a new release by going over a number of issues and evaluate them. In the mean time, you are perfectly safe by having your own modified version and switch over to a new release once it comes around.

**Comment by djamell** [comment]
Is there an estimated time for a new version including this fix?

And thanks @EPTamminga for your continued support of this excellent module.

**Comment by EPTamminga** [comment]
@djamell I have the new release (almost) at the top of my ToDo list, but normal work (and children & grand children activities) keep pushing it a bit downward. I'll work om it this week.

**Comment by Behnam-Emamian** [comment]
Hi Guys

I still have this problem.

Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'DotNetNuke.Modules.Events.EventInfoHelper+EventDateSort'.

**Comment by EPTamminga** [comment]
I have one of my developers working on DNN.Events. We converted it to C#, he is now working on removing some Telerik controls and getting the whole module packaging process into place. When the basics are working again, he will have a look at the issues.

**Comment by PeterCasper** [comment]
Ernst,

I currently use 20 sub-calendars to manage event security. Can he also please look at including sub-calendar names in the iCal output like that displayed on a parent calendar? I know an attempt to fix this was previously attempted however I could not get the test code to run.

Thank you.

**Comment by EPTamminga** [comment]
I know. This request is a bit more complex, but it is on the list and not forgotten.

**Pull request merged**
