### PR TITLE
Add missing LICENSE file

### PR DESCRIPTION
**Pull request by nvisionative**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/DNNCommunity/DNN.Events/pull/59%23issuecomment-352659117%22%2C%20%22https%3A//github.com/DNNCommunity/DNN.Events/pull/59%23issuecomment-352794874%22%2C%20%22https%3A//github.com/DNNCommunity/DNN.Events/pull/59%23issuecomment-352911122%22%2C%20%22https%3A//github.com/DNNCommunity/DNN.Events/pull/59%23issuecomment-352992263%22%2C%20%22https%3A//github.com/DNNCommunity/DNN.Events/pull/59%23issuecomment-368276966%22%2C%20%22https%3A//github.com/DNNCommunity/DNN.Events/pull/59%23issuecomment-368298877%22%2C%20%22https%3A//github.com/DNNCommunity/DNN.Events/pull/59%23issuecomment-368318716%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/DNNCommunity/DNN.Events/pull/59%23issuecomment-352659117%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40nvisionative%20%3A%20there%20is%20already%20a%20license%20file%20in%20the%20Installation%20folder.%20The%20install%20package%20builder%20%28MSBuild%29%20will%20take%20care%20of%20putting%20it%20in%20the%20install%20pack.%22%2C%20%22created_at%22%3A%20%222017-12-19T07%3A13%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/5859855%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/EPTamminga%22%7D%7D%2C%20%7B%22body%22%3A%20%22Oh%2C%20sorry%20%40EPTamminga%20-%20all%20the%20other%20DNN%20Community%20projects%20have%20it%20in%20their%20root%20folder%2C%20so%20when%20I%20didn%27t%20see%20it%20here%2C%20I%20just%20added%20it.%20%20%3A%29%22%2C%20%22created_at%22%3A%20%222017-12-19T15%3A37%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/4568451%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/nvisionative%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20think%20%40nvisionative%20is%20correct%2C%20each%20project%20should%20have%20a%20license%20file%20in%20the%20root%2C%20which%20will%20then%20show%20as%20the%20license%20on%20github.%20%22%2C%20%22created_at%22%3A%20%222017-12-19T22%3A51%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars0.githubusercontent.com/u/1823580%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/erikvb%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40erikvb%20OK.%20I%20did%20not%20know%20this.%20I%20will%20see%20if%20the%20MSBuild%20can%20be%20changed%20so%20it%20picks%20up%20the%20liicense%20file%20from%20the%20root%20i.s.o.%20the%20installation%20folder.%5Cr%5Cn%40nvisionative%20%3A%20%5C%22better%20be%20safe%20than%20sorry%5C%22.%22%2C%20%22created_at%22%3A%20%222017-12-20T08%3A01%3A17Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/5859855%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/EPTamminga%22%7D%7D%2C%20%7B%22body%22%3A%20%22Just%20checking%20in%20on%20the%20status%20of%20this%20pull%20request.%22%2C%20%22created_at%22%3A%20%222018-02-25T02%3A13%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/4568451%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/nvisionative%22%7D%7D%2C%20%7B%22body%22%3A%20%22In%20an%20update.%20I%20will%20move%20the%20existing%20license.txt%20to%20the%20root.%20This%20involves%20also%20changing%20the%20MSBuild%20task%20to%20create%20the%20install%20pack.%20%22%2C%20%22created_at%22%3A%20%222018-02-25T10%3A34%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/5859855%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/EPTamminga%22%7D%7D%2C%20%7B%22body%22%3A%20%22Okay%2C%20thanks.%22%2C%20%22created_at%22%3A%20%222018-02-25T15%3A35%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/4568451%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/nvisionative%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/DNNCommunity/DNN.Events/pull/59#issuecomment-352659117'>General Comment</a></b>
- <a href='https://github.com/EPTamminga'></a> @nvisionative : there is already a license file in the Installation folder. The install package builder (MSBuild) will take care of putting it in the install pack.
- <a href='https://github.com/nvisionative'></a> Oh, sorry @EPTamminga - all the other DNN Community projects have it in their root folder, so when I didn't see it here, I just added it.  :)
- <a href='https://github.com/erikvb'></a> I think @nvisionative is correct, each project should have a license file in the root, which will then show as the license on github.
- <a href='https://github.com/EPTamminga'></a> @erikvb OK. I did not know this. I will see if the MSBuild can be changed so it picks up the liicense file from the root i.s.o. the installation folder.
@nvisionative : "better be safe than sorry".
- <a href='https://github.com/nvisionative'></a> Just checking in on the status of this pull request.
- <a href='https://github.com/EPTamminga'></a> In an update. I will move the existing license.txt to the root. This involves also changing the MSBuild task to create the install pack.
- <a href='https://github.com/nvisionative'></a> Okay, thanks.

<a href='https://www.codereviewhub.com/DNNCommunity/DNN.Events/pull/59?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/DNNCommunity/DNN.Events/pull/59?approve=1'></a>&nbsp;<a href='https://github.com/DNNCommunity/DNN.Events/pull/59'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by EPTamminga** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/DNNCommunity/DNN.Events/pull/59'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by EPTamminga** [comment]
@nvisionative : there is already a license file in the Installation folder. The install package builder (MSBuild) will take care of putting it in the install pack.

**Comment by nvisionative** [comment]
Oh, sorry @EPTamminga - all the other DNN Community projects have it in their root folder, so when I didn't see it here, I just added it.  :)

**Comment by erikvb** [comment]
I think @nvisionative is correct, each project should have a license file in the root, which will then show as the license on github.

**Comment by EPTamminga** [comment]
@erikvb OK. I did not know this. I will see if the MSBuild can be changed so it picks up the liicense file from the root i.s.o. the installation folder.
@nvisionative : "better be safe than sorry".

**Comment by nvisionative** [comment]
Just checking in on the status of this pull request.

**Comment by EPTamminga** [comment]
In an update. I will move the existing license.txt to the root. This involves also changing the MSBuild task to create the install pack.

**Comment by nvisionative** [comment]
Okay, thanks.

**Pull request merged**
